### ISSUE TITLE
Source code missing

### ISSUE THREAD

**Issue by dhintermann-optos** [justinengelmann/RETFound_Green#2]
The archives (zip/tar.gz) from the release v0.1 contain only the readme file. I was wondering if the code for the initial training could be put into the main branch of the repo.

**Comment by justinengelmann** [comment]
Hi DHintermannViz,

Thanks for your interest in RETFound-Green.

That's intentional, please refer to the README:
"🚧 Under construction: At present, this repo contains the RETFound-Green model weights and basic instructions for usage. We're currently cleaning up and documenting the code for training and evaluation. Email us if you encounter any issues or would like a preview version."

The release is merely meant to hold the model weights, a trick I copied from the timm library.

Best wishes,
Justin
